### ISSUE TITLE
Licensing (GPLv2 vs v3)

### ISSUE THREAD

**Issue by audigex** [KubaP/ModernUKTrainset#5]
Hi guys

I noticed this project is released under GPLv3, which is great, but presents me with a problem. I was hoping to use the project as a basis to update some of the BRTrains project (which has a much trickier build process that my amateur ass can't get my head around), add some newer liveries, fix a couple of bugs (Turbostar liveries) etc.

However, BRTrains is (by necessity) under the GPLv2. The necessity coming from the fact that many of the graphics were originally created for the BROS set, which was GPLv2, and there's no way to contact the individual contributors and ask them to re-license them (in part because the records of exactly who created them have been lost)

Since the GPLv2 and GPLv3 aren't compatible (any derivative projects MUST be under the exact same license), that means I can't use the MUTS codebase alongside the BRTrains set

So I'm hoping that the fact there are two identifiable contributors here may mean that you're willing to switch to GPLv2 or simply dual-license the project, which would mean it can be continued/forked/used under either the GPLv2 or GPLv3 license.

Does that sound possible?

Thanks
Jon (Audigex)

**Comment by audigex** [comment]
That was insanely fast... thanks

**Comment by AlexGarrity** [comment]
No worries, have fun with modding OpenTTD.
Drop an issue if you have any problems with this stuff - it should all be alright but occasionally stuff slips through the cracks

Cheers,
Alex
